/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBrowseRouteImport } from './routes/_app/browse'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWordsRouteImport } from './routes/_app/words'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'
import { Route as WordsAddRouteImport } from './routes/words.add'
import { Route as AppWordsIndexRouteImport } from './routes/_app/words/index'
import { Route as AppWordsWordIdRouteImport } from './routes/_app/words/$wordId'
import { Route as ApiAudioArticleIdRouteImport } from './routes/api/audio.$articleId'
import { Route as ApiAuthDevRouteImport } from './routes/api/auth.dev'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth.google'
import { Route as ApiExtensionMeRouteImport } from './routes/api/extension.me'
import { Route as ApiExtensionWordsRouteImport } from './routes/api/extension.words'
import { Route as ApiWordAudioWordRouteImport } from './routes/api/word-audio.$word'
import { Route as ApiAudioArticleIdChunkRouteImport } from './routes/api/audio.$articleId.$chunk'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsRoute = AppWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AppRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsAddRoute = WordsAddRouteImport.update({
  id: '/words/add',
  path: '/words/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWordsIndexRoute = AppWordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWordsRoute,
} as any)
const AppWordsWordIdRoute = AppWordsWordIdRouteImport.update({
  id: '/$wordId',
  path: '/$wordId',
  getParentRoute: () => AppWordsRoute,
} as any)
const ApiAudioArticleIdRoute = ApiAudioArticleIdRouteImport.update({
  id: '/api/audio/$articleId',
  path: '/api/audio/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevRoute = ApiAuthDevRouteImport.update({
  id: '/api/auth/dev',
  path: '/api/auth/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionMeRoute = ApiExtensionMeRouteImport.update({
  id: '/api/extension/me',
  path: '/api/extension/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionWordsRoute = ApiExtensionWordsRouteImport.update({
  id: '/api/extension/words',
  path: '/api/extension/words',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordAudioWordRoute = ApiWordAudioWordRouteImport.update({
  id: '/api/word-audio/$word',
  path: '/api/word-audio/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioArticleIdChunkRoute = ApiAudioArticleIdChunkRouteImport.update({
  id: '/$chunk',
  path: '/$chunk',
  getParentRoute: () => ApiAudioArticleIdRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/browse': typeof AppBrowseRoute
  '/settings': typeof AppSettingsRoute
  '/words': typeof AppWordsRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/words/add': typeof WordsAddRoute
  '/words/$wordId': typeof AppWordsWordIdRoute
  '/api/audio/$articleId': typeof ApiAudioArticleIdRouteWithChildren
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/extension/words': typeof ApiExtensionWordsRoute
  '/api/word-audio/$word': typeof ApiWordAudioWordRoute
  '/words/': typeof AppWordsIndexRoute
  '/api/audio/$articleId/$chunk': typeof ApiAudioArticleIdChunkRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/browse': typeof AppBrowseRoute
  '/settings': typeof AppSettingsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/words/add': typeof WordsAddRoute
  '/': typeof AppIndexRoute
  '/words/$wordId': typeof AppWordsWordIdRoute
  '/api/audio/$articleId': typeof ApiAudioArticleIdRouteWithChildren
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/extension/words': typeof ApiExtensionWordsRoute
  '/api/word-audio/$word': typeof ApiWordAudioWordRoute
  '/words': typeof AppWordsIndexRoute
  '/api/audio/$articleId/$chunk': typeof ApiAudioArticleIdChunkRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/browse': typeof AppBrowseRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/words': typeof AppWordsRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/words/add': typeof WordsAddRoute
  '/_app/': typeof AppIndexRoute
  '/_app/words/$wordId': typeof AppWordsWordIdRoute
  '/api/audio/$articleId': typeof ApiAudioArticleIdRouteWithChildren
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/extension/words': typeof ApiExtensionWordsRoute
  '/api/word-audio/$word': typeof ApiWordAudioWordRoute
  '/_app/words/': typeof AppWordsIndexRoute
  '/api/audio/$articleId/$chunk': typeof ApiAudioArticleIdChunkRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/browse'
    | '/settings'
    | '/words'
    | '/lessons/$lessonId'
    | '/words/add'
    | '/words/$wordId'
    | '/api/audio/$articleId'
    | '/api/auth/dev'
    | '/api/auth/google'
    | '/api/extension/me'
    | '/api/extension/words'
    | '/api/word-audio/$word'
    | '/words/'
    | '/api/audio/$articleId/$chunk'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/welcome'
    | '/browse'
    | '/settings'
    | '/lessons/$lessonId'
    | '/words/add'
    | '/'
    | '/words/$wordId'
    | '/api/audio/$articleId'
    | '/api/auth/dev'
    | '/api/auth/google'
    | '/api/extension/me'
    | '/api/extension/words'
    | '/api/word-audio/$word'
    | '/words'
    | '/api/audio/$articleId/$chunk'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/welcome'
    | '/_app/browse'
    | '/_app/settings'
    | '/_app/words'
    | '/lessons/$lessonId'
    | '/words/add'
    | '/_app/'
    | '/_app/words/$wordId'
    | '/api/audio/$articleId'
    | '/api/auth/dev'
    | '/api/auth/google'
    | '/api/extension/me'
    | '/api/extension/words'
    | '/api/word-audio/$word'
    | '/_app/words/'
    | '/api/audio/$articleId/$chunk'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  WordsAddRoute: typeof WordsAddRoute
  ApiAudioArticleIdRoute: typeof ApiAudioArticleIdRouteWithChildren
  ApiAuthDevRoute: typeof ApiAuthDevRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiExtensionMeRoute: typeof ApiExtensionMeRoute
  ApiExtensionWordsRoute: typeof ApiExtensionWordsRoute
  ApiWordAudioWordRoute: typeof ApiWordAudioWordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/words': {
      id: '/_app/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof AppWordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/add': {
      id: '/words/add'
      path: '/words/add'
      fullPath: '/words/add'
      preLoaderRoute: typeof WordsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/words/': {
      id: '/_app/words/'
      path: '/'
      fullPath: '/words/'
      preLoaderRoute: typeof AppWordsIndexRouteImport
      parentRoute: typeof AppWordsRoute
    }
    '/_app/words/$wordId': {
      id: '/_app/words/$wordId'
      path: '/$wordId'
      fullPath: '/words/$wordId'
      preLoaderRoute: typeof AppWordsWordIdRouteImport
      parentRoute: typeof AppWordsRoute
    }
    '/api/audio/$articleId': {
      id: '/api/audio/$articleId'
      path: '/api/audio/$articleId'
      fullPath: '/api/audio/$articleId'
      preLoaderRoute: typeof ApiAudioArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev': {
      id: '/api/auth/dev'
      path: '/api/auth/dev'
      fullPath: '/api/auth/dev'
      preLoaderRoute: typeof ApiAuthDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/me': {
      id: '/api/extension/me'
      path: '/api/extension/me'
      fullPath: '/api/extension/me'
      preLoaderRoute: typeof ApiExtensionMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/words': {
      id: '/api/extension/words'
      path: '/api/extension/words'
      fullPath: '/api/extension/words'
      preLoaderRoute: typeof ApiExtensionWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/word-audio/$word': {
      id: '/api/word-audio/$word'
      path: '/api/word-audio/$word'
      fullPath: '/api/word-audio/$word'
      preLoaderRoute: typeof ApiWordAudioWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$articleId/$chunk': {
      id: '/api/audio/$articleId/$chunk'
      path: '/$chunk'
      fullPath: '/api/audio/$articleId/$chunk'
      preLoaderRoute: typeof ApiAudioArticleIdChunkRouteImport
      parentRoute: typeof ApiAudioArticleIdRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface AppWordsRouteChildren {
  AppWordsWordIdRoute: typeof AppWordsWordIdRoute
  AppWordsIndexRoute: typeof AppWordsIndexRoute
}

const AppWordsRouteChildren: AppWordsRouteChildren = {
  AppWordsWordIdRoute: AppWordsWordIdRoute,
  AppWordsIndexRoute: AppWordsIndexRoute,
}

const AppWordsRouteWithChildren = AppWordsRoute._addFileChildren(
  AppWordsRouteChildren,
)

interface AppRouteChildren {
  AppBrowseRoute: typeof AppBrowseRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWordsRoute: typeof AppWordsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrowseRoute: AppBrowseRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWordsRoute: AppWordsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAudioArticleIdRouteChildren {
  ApiAudioArticleIdChunkRoute: typeof ApiAudioArticleIdChunkRoute
}

const ApiAudioArticleIdRouteChildren: ApiAudioArticleIdRouteChildren = {
  ApiAudioArticleIdChunkRoute: ApiAudioArticleIdChunkRoute,
}

const ApiAudioArticleIdRouteWithChildren =
  ApiAudioArticleIdRoute._addFileChildren(ApiAudioArticleIdRouteChildren)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  WordsAddRoute: WordsAddRoute,
  ApiAudioArticleIdRoute: ApiAudioArticleIdRouteWithChildren,
  ApiAuthDevRoute: ApiAuthDevRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiExtensionMeRoute: ApiExtensionMeRoute,
  ApiExtensionWordsRoute: ApiExtensionWordsRoute,
  ApiWordAudioWordRoute: ApiWordAudioWordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
